### PR TITLE
Releasev1.5.0

### PR DESCRIPTION
**Pull request by baude**
* dependency updates
* code of conduct added

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM @Luap99 @mheon

**Comment by mheon** [comment]
/lgtm
/hold
CI seems stuck?

**Comment by Luap99** [comment]
> Scheduling was delayed due to a concurrency limit on community tasks

https://cirrus-ci.com/task/6314458402783232

@cevich PTAL

**Comment by cevich** [comment]
[This will prevent the problem from happening again](https://github.com/containers/netavark/pull/576).  Also Cirrus-Support changed some settings on their end that will help with this specific repository (and netavark too).

**Pull request merged**
