### PR TITLE
Cirrus: Update meta-task for EC2 image

### PR DESCRIPTION
**Pull request by cevich**
Also, switch to referencing the EC2 AMI by name-tag instead of ID.

### CODE REVIEW

**Comment by cevich** [comment]
@flouthoc help please.  Validation errors here I have no idea how to handle.  Maybe they came in b/c new CI VM images?  If not, then everybody's experiencing them :disappointed:

**Comment by flouthoc** [comment]
@cevich This should unblock https://github.com/containers/aardvark-dns/pull/208

**Comment by cevich** [comment]
force-push: rebased.

**Comment by cevich** [comment]
okay, this PR is ready to go.

**Review by lsm5 — APPROVED** [review]
/lgtm

**Pull request merged**
