### PR TITLE
Allow custom cargo binary path

### PR DESCRIPTION
**Pull request by lsm5**
This commit allows setting of a custom path for the cargo binary, with
default picking cargo from PATH.

This commit also includes the relevant changes to aardvark-dns.spec.rpkg
to generate debug packages along with some cosmetic changes.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
successful copr build with debuginfo enabled https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5485506/

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
> LGTM

@flouthoc thanks. I made a small change in the spec.rpkg file. The Makefile is the same. PTAL again. New build is at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5486582/

**Comment by lsm5** [comment]
good to go.

**Pull request merged**
