### PR TITLE
cleanup: perform cleanups for clippy

### PR DESCRIPTION
**Pull request by flouthoc**
Make `cargo clippy` happy and remove unwanted code.

### CODE REVIEW

**Comment by flouthoc** [comment]
This PR should be good but I still need to perform testing so `don't merge` till i test every case.

/hold

**Comment by flouthoc** [comment]
> @flouthoc: PR needs rebase.

ackd i'm testing this. hold still

**Comment by flouthoc** [comment]
@baude Sure.

**Comment by baude** [comment]
@flouthoc is this ready to go?

**Comment by baude** [comment]
@flouthoc please wrap this up

**Comment by flouthoc** [comment]
@baude Apologies for the delay. This should be good to go now.

**Pull request merged**
