### PR TITLE
makefile: remove windows specific libaries from vendor

### PR DESCRIPTION
**Pull request by flouthoc**
Modify `vendor-rm-windows` to remove windows specific libaries from
vendor directory.

### CODE REVIEW

**Comment by flouthoc** [comment]
@mheon @jnovy @baude This removes windows libraries from vendor.

**Comment by flouthoc** [comment]
Not sure how this will be backported though I don't see a branch for `v1.1.0-rhel` but I'll leave it for others to decide cause I think last release was also done manually so hopefully no issues there.

**Comment by flouthoc** [comment]
@lsm5 ^

**Comment by mheon** [comment]
LGTM

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
does this need to be branched after merge for rhel ?

**Comment by mheon** [comment]
What branch are we building using?

**Comment by lsm5** [comment]
> What branch are we building using?

let me look up current status

**Comment by lsm5** [comment]
I'm good to remove hold label if others are, I only added it to check if there were any branching discussions to be answered before merge.

**Comment by lsm5** [comment]
> so far it's the tag v1.1.0 that's being built. So maybe we could do a new tag, or build from a new v1.1.0-rhel branch. I think either should work. I'll defer to @jnovy

@TomSweeneyRedHat PTAL ^

**Comment by flouthoc** [comment]
/hold cancel
@jnovy Suggested a backport branch so once this is merged. I'll open a backport PR

**Pull request merged**
