### PR TITLE
cargo.toml: update info fields for packaging

### PR DESCRIPTION
**Pull request by flouthoc**
Update `cargo.toml` with fields necessary for packaging.

### CODE REVIEW

**Comment by flouthoc** [comment]
@mheon @Luap99 @baude @lsm5 PTAL following fields are needed for packaging. Same as https://github.com/containers/netavark/pull/320

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by flouthoc** [comment]
@mheon @lsm5 PTAL

**Comment by flouthoc** [comment]
Merge me pls.

**Pull request merged**
