### PR TITLE
[CI:BUILD] Packit: add Fedora downstream tasks

### PR DESCRIPTION
**Pull request by lsm5**
Get rid of `aardvark-dns.spec.rpkg` in favour of
`rpm/aardvark-dns.spec` which gets synced with fedora dist-git on every upstream release. The version in the new spec file is set to `0` by default and gets updated by packit automatically on every packit task.

Packit will automatically create a PR on fedora dist-git on every new upstream release. A sample PR will look like:
https://src.fedoraproject.org/rpms/container-selinux/pull-request/10#

A dry run for this can be triggered using:
`$ packit propose-downstream --local-content`

To run this command locally, you would need to have your packit user-configuration-file set.
Ref: https://packit.dev/docs/configuration/#user-configuration-file

along with a fedora api key created at:
https://src.fedoraproject.org/settings#nav-api-tab with sufficient ACLs.

With this PR, downstream Fedora spec will get synced with `rpm/aardvark-dns.spec` present upstream, so upstream will remain independent of downstream and the packaging process will become a part of upstream maintenance. The downstream tasks add zero extra cost to upstream release process (except an automatic github issue on downstream task failure).

### CODE REVIEW

**Comment by lsm5** [comment]
ignore PR until packit builds are fixed and draft status removed.

**Comment by lsm5** [comment]
@Luap99 @baude @mheon @flouthoc @edsantiago @cevich PTAL

**Review by cevich — APPROVED** [review]
LGTM (though I'm not an SME on packaging/packit).

**Comment by lsm5** [comment]
I think I can remove the changelog conditionals too. Give me a bit to verify.

**Comment by lsm5** [comment]
> I think I can remove the changelog conditionals too. Give me a bit to verify.

na, rhel8 needs manual changelog. No further change to this PR.

**Comment by lsm5** [comment]
> > I think I can remove the changelog conditionals too. Give me a bit to verify.
> 
> na, rhel8 needs manual changelog. No further change to this PR.

just when I thought no further change :|  ... never mind

**Comment by edsantiago** [comment]
Rats. I was reviewing just now, but didn't do a git-pr checkout, so now I'll never know what changed.

I think I'm going to skip future review of PRs like these. I'll be OK if CI passes, and then OK with future touch-up PRs.

**Comment by lsm5** [comment]
> Rats. I was reviewing just now, but didn't do a git-pr checkout, so now I'll never know what changed.
> 
> I think I'm going to skip future review of PRs like these. I'll be OK if CI passes, and then OK with future touch-up PRs.

@edsantiago the change was the additional commit that I haven't squashed yet.

**Comment by lsm5** [comment]
@edsantiago Feel free to skip such PRs, they don't affect upstream. I bother people cause I need someone to LGTM :) . Thanks!

**Review by edsantiago — APPROVED** [review]

**Comment by lsm5** [comment]
@Luap99 @mheon @flouthoc PTAL. Let's get this in hopefully before the next release. I got plans for a similar PR for netavark as well.

**Review by Luap99 — APPROVED** [review]
/lgtm

**Comment by Luap99** [comment]
FYI: Next release should be sometime next week

**Pull request merged**
