### PR TITLE
Add rpkg template for COPR autobuild

### PR DESCRIPTION
**Pull request by lsm5**
https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/message/3JORYRKDWFMJSR35Z4LIKDEXH2T5263H/

Also comment out docs install step in Makefile

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@flouthoc @baude @mheon @Luap99 @rhatdan PTAL.

Btw, I'm not the biggest fan of install targets depending on build targets. Would it be ok to have them separate? This would mean `make && make install` for people building from source, but it would also mean no extra `-nobuild` targets like the mess we have in podman.

### CODE REVIEW

**Comment by lsm5** [comment]
Let me know what the aardvark <-> netavark <-> podman install deps should look like. I can add them to the PRs.

**Comment by baude** [comment]
podman4 should require netavark, netavark should require aardvark

**Comment by baude** [comment]
LGTM

**Comment by lsm5** [comment]
> podman4 should require netavark, netavark should require aardvark

i'll update PRs for podman and netavark. This one should be good to go.

**Review by flouthoc — APPROVED** [review]

**Pull request merged**
