### PR TITLE
coredns: forward names with no ndots as well

### PR DESCRIPTION
**Pull request by Luap99**
Docker does this and there might be local names and a local resolver that otherwise cannot be resolved.

Fixes https://issues.redhat.com/browse/RHEL-61873

### CODE REVIEW

**Comment by baude** [comment]
yeah we discussed this ... LGTM @mheon ping

**Comment by mheon** [comment]
LGTM, but your tests are red

**Comment by Luap99** [comment]
yes tests need more work, some requests time out now instead of the nxdomain

One thing I realized instead of using slirp4netns and connecting to public dns servers maybe I should do the dnsmasq setup for each test with a few dummy records we can query. This solves our network dependency and some other issues, i.e. I can add big dns entries that must use tcp and cannot be resolved via udp which gives better coverage overall.
But I put this below all the other prority work so far so I didn't get to it yet.

**Comment by Luap99** [comment]
@mheon @baude PTAL again, now with a bunch of test changes that I think are better as I removed external network access from the tests

**Pull request merged**
