### PR TITLE
tmt: install dnsmasq dependency

### PR DESCRIPTION
**Pull request by Luap99**
We need this as of commit e6ce710660.

### CODE REVIEW

**Comment by Luap99** [comment]
Ok this makes the fedora tests work again.

**Review by lsm5 — APPROVED** [review]
LGTM

I'll remove the rhel tests from aardvark-dns as well. If we're not testing on netavark, no need here either.

**Comment by Luap99** [comment]
@lsm5 please merge this, there really isn't much of a point forcing a second review on such small non code changes.

**Comment by Luap99** [comment]
nevermind I see you already added this in https://github.com/containers/aardvark-dns/pull/491

**Pull request closed without merging**
