### PR TITLE
tests: add slirp4netns to connect the host netns

### PR DESCRIPTION
**Pull request by Luap99**
To test upstream resolvers we need a connection to the internet. We can
use slirp4netns for this. Also create a new mount namespace so that we
can bind mount a correct resolv.conf which points to the slirp4netns
resolver.

### CODE REVIEW

**Comment by Luap99** [comment]
I had to wait for new CI images with slirp4netns. I think this should work now let me rebase and see

**Comment by Luap99** [comment]
@baude @mheon @flouthoc PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
