### PR TITLE
Cirrus: Identify precisely where binary came from

### PR DESCRIPTION
**Pull request by cevich**
Port of https://github.com/containers/netavark/pull/191 for identical
purpose.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Binary zip contains `aardvark-dns.info` file with:
```
repo: https://github.com/containers/aardvark-dns.git
branch: main
title: Cirrus: Identify precisely where binary came from
commit: 33a375f81fcc972f6692d10ee01dc30c9dc9fdb6
build: https://cirrus-ci.com/build/5407428840783872
task: https://cirrus-ci.com/task/6550043049066496
```

**Comment by baude** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]

**Pull request merged**
