### PR TITLE
fix: dedup network names

### LINKED ISSUE #120: Aardvark returns two identical A records
Hello!

I've been playing with Aardvark (1.0.2) with Podman (4.0.3) and I could discover why Nginx's DNS client on an custom bridge network was failing to resolve DNS names. Nginx was complaining about an "unexpected A record" - upon digging, it appears Aardvark is returning duplicate records that Nginx couldn't handle.

Here's an example:

```
# dig cyberchef

; <<>> DiG 9.16.27-Debian <<>> cyberchef
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31292
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cyberchef.			IN	A

;; ANSWER SECTION:
cyberchef.		600	IN	A	172.18.0.3
cyberchef.		600	IN	A	172.18.0.3

;; Query time: 0 msec
;; SERVER: 10.89.0.1#53(10.89.0.1)
;; WHEN: Wed Apr 20 15:26:43 UTC 2022
;; MSG SIZE  rcvd: 52
```

This behavior, while not deal-breaking (some clients handle it gracefully), can cause unexpected behavior with some DNS clients. It's also different from the default Docker behavior where only a single record is returned.

I'm happy to provide more information as needed.

### PR DESCRIPTION
**Pull request by dzvon**
Fixes #120

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
Hi @dzvon , Thank you so much for the patch. Patch looks good to me and appears to solve the issue.

Could add a commit description like i.e `container_ip` to `network` membership should not contain duplicate membership entry.

Thanks again for your time and patch.

**Comment by flouthoc** [comment]
@baude @mheon @Luap99 PTAL

**Comment by dzvon** [comment]
@flouthoc Done. :)

**Review by Luap99 — COMMENTED** [review]
Instead of looping over all entries again could we stop adding duplicated entries in the first place?

**Comment by flouthoc** [comment]
@dzvon If you can check if `s` is already here you can just not append it https://github.com/containers/aardvark-dns/blob/main/src/config/mod.rs#L152

**Comment by dzvon** [comment]
@flouthoc I've put a debug statement here,

```rust
                    ip_networks.append(&mut s.clone());
                    log::debug!("s is {:?}", s);
```

the output is

```console
Apr 25 16:56:38 archlinux aardvark-dns[750366]: s is ["test", "test"]
Apr 25 16:56:38 archlinux aardvark-dns[750366]: s is ["test", "test"]
```

So, it seems like s is already duplicated. Probably we can add a check here https://github.com/containers/aardvark-dns/blob/f81c01df64e4ff3f141294b8b97fc58ac1ced329/src/config/mod.rs#L102

**Review by flouthoc — APPROVED** [review]
LGTM I tried running the patch solves the reported issue.

**Comment by Luap99** [comment]
Can we add a test for this? I would like to avoid regression.

**Comment by dzvon** [comment]
@Luap99 Sure.

But I encountered some problems when I ran the test script in podman rootless mode. I haven't added anything yet.

<details>
  <summary>Click to expand</summary>

```console
➜  aardvark-dns git:(patch-1) podman unshare --rootless-netns bats test/100-basic-name-resolution.bats
 ✗ basic container - dns itself
   (from function `assert' in file test/helpers.bash, line 197,
    in test file test/100-basic-name-resolution.bats, line 19)
     `assert "$ip_a1"' failed
   /usr/bin/slirp4netns
    nsenter -m -n -t 440102 mount --bind /var/tmp/aardvark_bats.hEEUks/resolv.conf /etc/resolv.conf
    nsenter -m -n -t 440102 ip addr
   1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
       link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
       inet 127.0.0.1/8 scope host lo
          valid_lft forever preferred_lft forever
       inet6 ::1/128 scope host
          valid_lft forever preferred_lft forever
   2: tap0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
       link/ether 3a:76:c8:ce:fb:81 brd ff:ff:ff:ff:ff:ff
       inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
          valid_lft forever preferred_lft forever
       inet6 fe80::3876:c8ff:fece:fb81/64 scope link tentative
          valid_lft forever preferred_lft forever
    nsenter -m -n -t 440102 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.hEEUks -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns setup /proc/440136/ns/net
   {"podman1":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.241.119.1"],"interfaces":{"eth0":{"mac_address":"5a:bf:0e:25:2f:68","subnets":[{"gateway":"10.241.119.1","ipnet":"10.241.119.250/24"}]}}}}
    nsenter -n -t 440136 dig +short aone @10.241.119.1
   ;; communications error to 10.241.119.1#53: connection refused
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: [no test name given]
   #| expected: '10.241.119.250'
   #|   actual: ';; communications error to 10.241.119.1#53: connection refused'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    nsenter -m -n -t 440102 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.hEEUks -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns teardown /proc/440136/ns/net
   440102
 ✗ basic container - dns itself with long network name
   (from function `assert' in file test/helpers.bash, line 197,
    in test file test/100-basic-name-resolution.bats, line 36)
     `assert "$ip_a1"' failed
    nsenter -m -n -t 440274 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.QXpRUr -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns setup /proc/440300/ns/net
   {"podman11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.229.67.1"],"interfaces":{"eth0":{"mac_address":"5a:3d:26:06:a8:07","subnets":[{"gateway":"10.229.67.1","ipnet":"10.229.67.85/24"}]}}}}
    nsenter -n -t 440300 dig +short aone @10.229.67.1
   ;; communications error to 10.229.67.1#53: connection refused
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: [no test name given]
   #| expected: '10.229.67.85'
   #|   actual: ';; communications error to 10.229.67.1#53: connection refused'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    nsenter -m -n -t 440274 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.QXpRUr -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns teardown /proc/440300/ns/net
   440274
 ✗ two containers on the same network
   (from function `assert' in file test/helpers.bash, line 197,
    in test file test/100-basic-name-resolution.bats, line 58)
     `assert "$a2_ip"' failed
    nsenter -m -n -t 440438 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.uzMu9S -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns setup /proc/440464/ns/net
   {"podman1":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.50.184.1"],"interfaces":{"eth0":{"mac_address":"a2:90:c9:99:09:87","subnets":[{"gateway":"10.50.184.1","ipnet":"10.50.184.193/24"}]}}}}
    nsenter -m -n -t 440438 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.uzMu9S -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns setup /proc/440557/ns/net
   {"podman1":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.50.184.1"],"interfaces":{"eth0":{"mac_address":"62:f6:6c:5f:a7:cd","subnets":[{"gateway":"10.50.184.1","ipnet":"10.50.184.172/24"}]}}}}
    nsenter -n -t 440464 dig +short atwo @10.50.184.1
   ;; communications error to 10.50.184.1#53: connection refused
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: [no test name given]
   #| expected: '10.50.184.172'
   #|   actual: ';; communications error to 10.50.184.1#53: connection refused'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    nsenter -m -n -t 440438 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.uzMu9S -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns teardown /proc/440464/ns/net
    nsenter -m -n -t 440438 /usr/lib/podman/netavark --config /var/tmp/aardvark_bats.uzMu9S -a /home/pvon/Documents/aardvark-dns/target/debug/aardvark-dns teardown /proc/440557/ns/net
   440438

3 tests, 3 failures
```
</details>

After some debug, found this.
```console
   {"podman1":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.183.69.1"],"interfaces":{"eth0":{"mac_address":"42:4d:98:f8:cc:f0","subnets":[{"gateway":"10.183.69.1","ipnet":"10.183.69.162/24"}]}}}}
   [DEBUG netavark::commands::setup] "Setup complete"
   Failed to connect to bus: Operation not permitted
    nsenter -n -t 454937 dig +short atwo @10.183.69.1
   ;; communications error to 10.183.69.1#53: connection refused
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: [no test name given]
   #| expected: '10.183.69.162'
   #|   actual: ';; communications error to 10.183.69.1#53: connection refused'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

> `Failed to connect to bus: Operation not permitted`

It looks like an error related to systemd. Am I missing something?

I want to pass the test locally, so it can be convenient to add a new test.

**Comment by JCBird1012** [comment]
> @Luap99 Sure.
> 
> But I encountered some problems when I ran the test script in podman rootless mode. I haven't added anything yet.
> 
> Click to expand
> After some debug, found this.
> 
> ```
>    {"podman1":{"dns_search_domains":["dns.podman"],"dns_server_ips":["10.183.69.1"],"interfaces":{"eth0":{"mac_address":"42:4d:98:f8:cc:f0","subnets":[{"gateway":"10.183.69.1","ipnet":"10.183.69.162/24"}]}}}}
>    [DEBUG netavark::commands::setup] "Setup complete"
>    Failed to connect to bus: Operation not permitted
>     nsenter -n -t 454937 dig +short atwo @10.183.69.1
>    ;; communications error to 10.183.69.1#53: connection refused
>    #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
>    #|     FAIL: [no test name given]
>    #| expected: '10.183.69.162'
>    #|   actual: ';; communications error to 10.183.69.1#53: connection refused'
>    #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
>  > Failed to connect to bus: Operation not permitted
> 
> It looks like an error related to systemd. Am I missing something?
> 
> I want to pass the test locally, so it can be convenient to add a new test.

I don’t know the exact circumstances of your test setup - but systemd won’t work in non-privileged containers - it requires `CAP_SYS_ADMIN` - if your image is using systemd-resolved, that could *potentially* be the problem.

**Comment by Luap99** [comment]
Sorry I missed the ping. I am not sure if rootless works. I never tried it with the aardvark tests.

For the systemd error you likely do not have a valid systemd user session. This should not require root.

**Comment by Luap99** [comment]
@dzvon Thanks, we will merge this since we want to create new release soon.

We will add a test later.

**Comment by dzvon** [comment]
@Luap99 Sorry for late response, I'm kind of busy lately.

**Pull request merged**
