### PR TITLE
run cargo update

### PR DESCRIPTION
**Pull request by Luap99**
Updates a lot of indirect dependencies, seems like renovate does not take care of it? I don't think dependabot did either so it's not a new thing.

### CODE REVIEW

**Comment by Luap99** [comment]
@flouthoc @mheon PTAL

cc @cevich Any idea if we can get renovate to take care of this as well?

**Comment by mheon** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Comment by cevich** [comment]
> Any idea if we can get renovate to take care of this as well?

It doesn't appear it can.  At the moment, the only "manager" module for Rust is called 'cargo'.  [The documentation for it](https://docs.renovatebot.com/modules/manager/cargo/#additional-information) suggests it reads `Cargo.toml`, then proposes updates w/ corresponding changes to the lock file.  The [Rust language documentation](https://docs.renovatebot.com/rust/) is even more clear.

Is it possible (and/or sensible) to make all the indirect deps into direct deps?  My guess is this isn't practicle.

Assuming there's a cargo command that can do this, another possible solution could be to use a github-actions workflow.  I think I came across a github action that can open PRs.  @Luap99 
 would you like me to investigate that more?

**Comment by Luap99** [comment]
> Assuming there's a cargo command that can do this

As the title say `cargo update`, but there is no reason to over engineer this, I only run this once before we make a release every few months and it takes basically no time so I don't think it is a problem to do it manually. I was just asking because renovate has a lot of options so I thought there might be something.

**Comment by cevich** [comment]
> I was just asking because renovate has a lot of options so I thought there might be something.

Nope, it was good of you to ask, and I'm happy to check.

**Pull request merged**
