### PR TITLE
COPR: Fix build and remove unused files

### PR DESCRIPTION
**Pull request by lsm5**
Makefile: add `mock-rpm` target

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Let's wait for [netavark copr build](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/3289486/) to succeed.

@Luap99 @baude @rhatdan @flouthoc @mheon PTAL

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by lsm5** [comment]
thanks, i'll remove work-in-progress label once the netavark build succeeds.

**Pull request merged**
